
enum authorities {
    DEFAULT = "DEFAULT",
    USER_MODIFY = "USER_MODIFY",
    USER_DELETE = "USER_DELETE",
    MODIFY_FOREIGN_POST = "MODIFY_FOREIGN_POST",
    DELETE_FOREIGN_POST = "DELETE_FOREIGN_POST"
}


export default authorities;
